/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// TypeScript 6 requires an ambient declaration for side-effect CSS imports (e.g. `./global.css`
// in App.tsx) that neither nativewind nor react-native-css-interop ship.
declare module '*.css';
